name: Deploy Sport al Parco 2026

on:
  push:
    branches:
      - main # o 'master' a seconda di come si chiama il tuo ramo principale

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: 'deployment.outputs.page_url' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v6 # Aggiornato per Node.js 24

      - name: Configura Pages
        uses: actions/configure-pages@v5

      - name: Carica Artefatti
        uses: actions/upload-pages-artifact@v3 # Versione corretta e aggiornata per Node.js 24
        with:
          path: '.' # Carica tutti i file della cartella principale (index.html, manifest.json, sw.js, icone)

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
